language: bash
services: docker

env:
  - VERSION=5.6
  - VERSION=5.5

install:
  - git clone https://github.com/amine7536/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="percona:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
